CREATE TABLE BookInfo (
    `Index` INT,
    `Title` VARCHAR(47) CHARACTER SET utf8,
    `Author` VARCHAR(27) CHARACTER SET utf8,
    `Summary` VARCHAR(821) CHARACTER SET utf8,
    `Word_Count` INT,
    `Reading_Ease` NUMERIC(4, 2),
    `Estimated_Reading_Time` VARCHAR(7) CHARACTER SET utf8
);
INSERT INTO BookInfo VALUES (1,'The Warden','Anthony Trollope','The Warden is concerned with the unassuming Rev. Septimus Harding| who has for many years been the Warden of Hiram’s Hospital in the fictional town of Barchester. This “hospital” is what we would today probably call an aged-care or retirement home. It was established under the provisions of a will to look after the needs of old men too feeble to work any longer and unable to support themselves. Mr. Harding benefits financially from his position| though the duties are very slight.',72777,64.14,'4h 25m');
INSERT INTO BookInfo VALUES (3,'Phantastes','George MacDonald','Phantastes was published in 1858. It tells the story of Anodos| who| on coming of age| is examining the effects of his deceased father. To his astonishment| in doing so he sees an apparition of a fairy woman| who tells him that he has some fairy blood and conveys him to Fairy Land.',69195,74.22,'4h 12m');
INSERT INTO BookInfo VALUES (4,'A Yankee in Canada','Henry David Thoreau','In the fall of 1850| Henry David Thoreau briefly visited Quebec with Ellery Channing. In this book| Thoreau describes the cities and homes| people and customs| and rivers and plants of that part of Canada.',28337,61.4,'1h 44m');
INSERT INTO BookInfo VALUES (6,'The Thirty-Nine Steps','John Buchan','Published in 1915| The Thirty-Nine Steps is a thriller set in Britain on the eve of the First World War.',41567,80.62,'2h 32m');
INSERT INTO BookInfo VALUES (8,'The Hound of the Baskervilles','Arthur Conan Doyle','It would be hard to nominate a more well-known character in English literature than that of the austere analytical detective Sherlock Holmes| created by Arthur Conan Doyle in the late 1880s. Holmes| alongside his friend and biographer Dr. John Watson| appeared in two initial novels and dozens of short stories serialised in popular magazines| attracting a devoted| almost fanatical following which continues to this day.',59643,80.92,'3h 37m');
INSERT INTO BookInfo VALUES (10,'Nightmare Abbey','Thomas Love Peacock','Published in 1818| Peacock’s novella Nightmare Abbey is a gentle satire of the then-popular gothic movement in literature. He pokes fun at the genre’s obsessions and most of the book’s characters are caricatures of well-known personages of the time.',26835,61.06,'1h 38m');
INSERT INTO BookInfo VALUES (13,'The Life and Adventures of Robinson Crusoe','Daniel Defoe','Robinson Crusoe is of the most popular books ever written in the English language| published in innumerable editions and translated into almost every language of the world| not to mention the many versions created in film| television and even radio. First published in 1719| it can also claim to be one of the first novels ever written in English.',121248,44.48,'7h 21m');
INSERT INTO BookInfo VALUES (16,'The Moonstone','Wilkie Collins','The “Moonstone” of the title is a large but flawed diamond| looted from India at the time of the Mutiny by an unscrupulous British officer. Many years later| estranged from his family due to his licentious lifestyle| the officer bequeaths the diamond to his sister’s daughter| Rachel Verrinder| to be given to her on her 18th birthday. Due to the ill-omens surrounding the gem| this may have been an act of revenge rather than reconciliation. The diamond| it appears| was taken from a statue of the Moon God worshipped by a Hindu cult| and it has long been sought by a group of Brahmins determined to return it to their temple.',198514,72.46,'12h 2m');
INSERT INTO BookInfo VALUES (17,'The Works of Max Beerbohm','Max Beerbohm','The Works of Max Beerbohm is a collection of satirical essays by Max Beerbohm. It was published in 1896 at The Bodley Head| his publisher John Lane contributing a detailed bibliography of the works of the author| then aged 24. Before their publication as a book| the essays had appeared in prominent literary periodicals such as The Yellow Book and The Savoy. Most of the essays were written while he was a student at Oxford| although he had left Merton College in 1894. By then he was already known as a caricaturist| parodist and essayist and well acquainted with the writers and artists connected with The Bodley Head| notably Aubrey Beardsley and Oscar Wilde.',32802,69.56,'2h 49m');
INSERT INTO BookInfo VALUES (19,'Captain Blood','Rafael Sabatini','Peter Blood| with experience as a soldier and sailor| is practicing medicine in Bridgewater| England| when he inadvertently gets caught up in a rebellion being waged by the Duke of Monmouth. After being convicted of treason| Blood and some of the rebels are sentenced to slavery in the Caribbean. The year is 1688.',115076,72.56,'6h 59m');
INSERT INTO BookInfo VALUES (20,'Bleak House','Charles Dickens','Bleak House| completed by Dickens in 1853| tells several interlocking story-lines and features a host of colorful characters. Though very difficult to summarise| the novel centers around the decades-long legal case of Jarndyce and Jarndyce| involving the fair distribution of assets of a valuable estate. The case is mired in the legal quagmire of the Court of Chancery| whose byzantine and sluggish workings Dickens spares no effort to expose and condemn. Dickens also exposes the miserable condition of the poor| living in squalid| pestilential circumstances.',359511,71.34,'21h 48m');
INSERT INTO BookInfo VALUES (21,'Parnassus on Wheels','Christopher Morley','Parnassus on Wheels is Christopher Morley’s first novel| and the first of two written from a woman’s perspective| the second being The Haunted Bookshop| this book’s sequel. Parnassus on Wheels was inspired by a novel by David Grayson (pseudonym of Ray Stannard Baker) called The Friendly Road| and is prefaced by a letter to Grayson from Morley. The word “Parnassus” from the title refers to “Mount Parnassus|” the home of the Muses in Greek mythology.',36830,82.24,'2h 14m');
INSERT INTO BookInfo VALUES (22,'Through the Looking-Glass','Lewis Carroll','Alice dreams herself into a mirror version of Wonderland| a whimsical land of talking flowers| and chess pieces| and a fighting lion and unicorn| and crosses sections of a life-size chess board. Upon reaching the Eighth Square| she is crowned a queen and the Red and White Queens throw her her very own dinner party to celebrate.',30578,81.43,'1h 52m');
INSERT INTO BookInfo VALUES (23,'The Pit-Prop Syndicate','Freeman Wills Crofts','The Pit-Prop Syndicate is a story from the beginning of the golden age of crime fiction. Seymour Merriman| a British wine merchant on business in France| happens upon a syndicate manufacturing pit-props⁠—beams used to prop up mine tunnels⁠—but his eye is caught by one odd detail: their lorry’s numberplate mysteriously changes. With the help of his friend Hilliard from the Excise department they dig deeper and uncover a dangerous conspiracy.',97400,71.75,'5h 55m');
INSERT INTO BookInfo VALUES (24,'Poetry','John Keats','John Keats’ poems are a major part of the second wave of English Romantic poetry. They portray settings loaded with symbolism and sensuality| and draw heavily on Greek and Roman myth along with romanticised tales of chivalry. Keats died in 1821 at the young age of 25| having written the majority of his work in less than four years. While not appreciated during his lifetime| he has gone on to become one of the most loved of the Romantic poets| and has provided inspiration to authors as diverse as Oscar Wilde| Wilfred Owen and Neil Gaiman.',96359,69.55,'5h 51m');
INSERT INTO BookInfo VALUES (25,'Kim','Rudyard Kipling','Rudyard Kipling’s novel Kim| published in 1901| tells the story of Kimberly O’Hara (“Kim”)| the orphaned son of an Anglo-Irish soldier| who grows up as a street-urchin on the streets of Lahore in India during the time of the British Raj. Knowing little of his parentage| he is as much a native as his companions| speaking Hindi and Urdu rather than English| cunning and street-wise.',106656,82.85,'6h 28m');
INSERT INTO BookInfo VALUES (28,'Silas Marner','George Eliot','In Silas Marner| author George Eliot (the pen name of Mary Ann Evans) introduces an embittered linen weaver who withdraws from society after a betrayal of trust. He retreats to work his loom or count and re-count his accumulated gold and silver. The abrupt theft of his money sends Marner into despair| which is interrupted just as suddenly by the appearance of an abandoned infant on his hearth. Marner adopts and raises the child| finding a new place among his community.',73444,62.01,'4h 28m');
INSERT INTO BookInfo VALUES (31,'Alice Adams','Booth Tarkington','Alice Adams is Booth Tarkington’s second novel to win a Pulitzer Prize| just three years after his novel The Magnificent Ambersons won it. The novel tells the story of Alice| a Midwestern girl who grows up in a lower-middle-class family just after World War I. Alice meets a wealthy young man and tries to win his affection| despite her lower-class upbringing.',88363,73.58,'5h 22m');
INSERT INTO BookInfo VALUES (33,'The Woman in White','Wilkie Collins','The Woman in White tells the story of Walter Hartright| a young and impoverished drawing teacher who falls in love with his aristocratic pupil| Laura Fairlie. He cannot hope to marry her| however| and she is married off against her will to a baronet| Sir Percival Glyde| who is seeking her fortune. The terms of her marriage settlement prevent Glyde accessing her money while she lives| so together with his deceptively charming and cunning friend| Count Fosco| they hatch an unscrupulous deception to do so nonetheless. In an early 19th Century version of “identity theft|” they contrive to fake Laura’s death and confine her to a mental asylum. Their plot is eventually uncovered and exposed by Hartright with the help of Laura’s resourceful half-sister| Marian Halcombe.',249593,69.92,'15h 8m');
INSERT INTO BookInfo VALUES (36,'No Name','Wilkie Collins','No Name is set in England during the 1840s. It follows the fortunes of two sisters| Magdalen Vanstone and her older sister Norah. Their comfortable upper-middle-class lives are shockingly disrupted when| after the sudden deaths of their parents| they discover that they are disinherited and left without either name or fortune. The headstrong Magdalen vows to recover their inheritance| by fair means or foul. Her increasing desperation makes her vulnerable to a wily confidence trickster| Captain Wragge| who promises to assist her in return for a cut of the profits.',268974,72.16,'16h 19m');
INSERT INTO BookInfo VALUES (37,'Vanity Fair','William Makepeace Thackeray','Vanity Fair is perhaps Thackeray’s most famous novel. First serialized over the course of 19 volumes in Punch Magazine and first printed as a single volume in 1849| the novel cemented Thackeray’s literary fame and kept him busy with frequent revisions and even lecture circuits.',308437,66.57,'18h 42m');
INSERT INTO BookInfo VALUES (41,'The Riddle of the Sands','Erskine Childers','The Riddle of the Sands is one of the earliest examples of the spy novel genre| and became hugely popular shortly after its publication. Childers carefully interweaves fiction with real-world places| events| and politics| making for an extremely convincing story of invasion—so convincing that some (perhaps erroneously) credit the novel with spurring the creation of new English naval bases. The framing device| where Childers pretends to be an editor presenting a factual account| only adds to the believability of the story.',110616,70.63,'6h 43m');
INSERT INTO BookInfo VALUES (45,'Lost Face','Jack London','The first anthology of short stories by Jack London| Lost Face tells seven stories about the Klondike gold rush. In “Lost Face|” the fur thief Subienkow faces gruesome torture and execution by a tribe of Indians| armed with only his wits. “Trust” is a story about the dangers of the Yukon River. Jack London’s best known short story| “To Build a Fire|” tells the story of a nameless man and his dog attempting to survive in the frozen Northern Territory. In “That Spot|” the eponymous Spot is a very unusual Yukon sled dog. “Flush of Gold” is a love story set against the harsh backdrop of the Yukon. “The Passing of Marcus O’Brien” deals the tale of the fair-but-tough Judge Marcus O’Brien in the settlement of Red Cow. “The Wit of Porportuk” tells the tale of El-Soo and Porportuk| two Indians among the white settlers.',41548,82.24,'2h 32m');
INSERT INTO BookInfo VALUES (46,'Gitanjali','Rabindranath Tagore','Widely regarded as one of the most important figures in Indian (and more specifically Bengali) literary history| Rabindranath Tagore was the first Indian (and indeed the first person outside Europe) to win the Nobel Prize in Literature| largely in recognition of his “spiritual offering of songs|” Gitanjali.',14605,71.56,'5h 4m');
INSERT INTO BookInfo VALUES (47,'The Magnificent Ambersons','Booth Tarkington','The Magnificent Ambersons| winner of the 1919 Pulitzer prize| is considered by many to be Booth Tarkington’s finest novel and an American classic. The story is set in the Midwest| where George| the spoiled and oblivious scion of an old-money family| must cope with their waning fortunes and the rise of industry barons in the automobile age.',103582,71.14,'6h 17m');
INSERT INTO BookInfo VALUES (48,'Scaramouche','Rafael Sabatini','Scaramouche tells the tale of André-Louis Moreau| a young lawyer in Brittany. When his friend is killed by an unremorseful landowner| Moreau swears revenge and begins a life of adventure on the run. His travels lead him to joining a traveling theater troupe| becoming a master swordsman| and even to revolution.',132139,73.68,'8h 1m');
INSERT INTO BookInfo VALUES (49,'Sartor Resartus','Thomas Carlyle','Sartor Resartus was a strange and new book when it was first published in 1833| and in many ways it remains a strange and new book today. The bulk of the novel takes the form of the a commentary on the life and works of the fictional Diogenes Teufelsdröckh| a sort of renaissance-man German philosopher who develops a “Philosophy of Clothes.” The commentary is composed by a fictional English commentator| known only as the “Editor”; the Editor claims to have translated many of Teufelsdröckh’s ideas and quotes from German. As the commentary progresses| the Editor receives a bag of paper scraps on which are written various autobiographical fragments from Teufelsdröckh’s life. The Editor’s attempts to organize and interpret these scraps forms the second part of the novel.',80373,48.17,'4h 53m');
INSERT INTO BookInfo VALUES (53,'Zuleika Dobson','Max Beerbohm','Max Beerbohm earned his fame as a caricaturist and essayist| and Zuleika Dobson is his only novel. Despite that| Zuleika has earned no small measure of fame| with the Modern Library ranking it 59th in its “100 Best English-Language Novels of the 20th Century.” Beerbohm’s essays were famous for their sharp wit and humor| and Zuleika follows in that tradition—Beerbohm himself called the novel “the work of a leisurely essayist amusing himself with a narrative idea.”',81907,74.49,'4h 58m');
INSERT INTO BookInfo VALUES (54,'A Strange Manuscript Found in a Copper Cylinder','James De Mille','A Strange Manuscript Found in a Copper Cylinder is perhaps James De Mille’s most popular book; sadly| De Mille didn’t get to see this novel grow in popularity| as it was first serialized posthumously| in Harper’s Weekly. De Mille had written the novel before the “lost world” genre had become saturated| meaning many of the ideas were fresh and original for the time in which it was written. But| since he didn’t succeed in publishing it during his lifetime| by the time the novel was made public other authors like H. Rider Haggard had made the ideas and plot clichéd.',87187,69.82,'5h 18m');
INSERT INTO BookInfo VALUES (56,'On Liberty','John Stuart Mill','John Stuart Mill was a prolific and well-regarded author and philosopher in his day| but perhaps his most enduring work is On Liberty| an essay developed over several years and with significant input from his wife. In it| he applies his views on the Utilitarian ethical theory to systems of society and governance. The result became one of the most influential essays on liberal political thought in modern history.',50937,34.43,'3h 6m');
INSERT INTO BookInfo VALUES (57,'The Gadfly','Ethel Voynich','The Gadfly is set in 1840s Italy| at a time when the the country was chafing under Austrian rule. The titular character is a charming| witty writer of pointed political satires who finds himself running with a crowd of revolutionaries. The plot develops as the revolutionaries struggle against the government and as the Gadfly struggles with a mysterious hatred of the Church| and of a certain Cardinal.',102319,72.56,'6h 13m');
INSERT INTO BookInfo VALUES (59,'The Shaving of Shagpat','George Meredith','The Shaving of Shagpat isn’t just George Meredith’s first published novel| it’s also his only foray into fantasy literature. Shagpat sold poorly in its day despite good reviews| and after its disappointing sales Meredith pursed a career as a writer of romantic fiction instead. Despite its poor financial reception| Shagpat enjoys a good modern reputation and remains a classic of fantasy literature| with George Eliot going so far as to call it a “work of genius.”',92390,71.38,'5h 36m');
INSERT INTO BookInfo VALUES (60,'The Secret Adversary','Agatha Christie','The Secret Adversary| Agatha Christie’s second novel| introduces Tommy and Tuppence| the two much-loved mystery-solving adventurers.',77902,78.14,'4h 44m');
INSERT INTO BookInfo VALUES (61,'The Castle of Otranto','Horace Walpole','The Castle of Otranto is considered to be the first “Gothic” novel—that is| containing a combination of tropes| like hidden passages| haunted paintings| mysterious sounds| skeletal ghosts| ancestral curses| and unexplained deaths| that essentially invented the genre later made famous by authors like Edgar Allan Poe| Bram Stoker| or Henry James. Walpole made a point of creating a novel that blends supernatural elements with more realistic depictions of characters and events.',37056,69.41,'2h 15m');
INSERT INTO BookInfo VALUES (62,'Table-Talk','William Hazlitt','William Hazlitt was a well-regarded critic and essayist in his day| and Table-Talk| a collection of some of his more popular short essays| is perhaps his best-remembered work.',152822,52.12,'9h 16m');
INSERT INTO BookInfo VALUES (64,'The Princess and the Goblin','George MacDonald','The Princess and the Goblin is a children’s fantasy novel in the vein of the best classic fairy tales. The simple narrative follows Princess Irene as she discovers a ghostly relative living in a castle tower only she can access. During a walk outside one day| she encounters the threat of the lair of goblins living near the castle—and meets a new friend| a young miner named Curdie. She and Curdie must stop the goblin threat before they can carry out their evil plot.',51773,79.5,'3h 9m');
INSERT INTO BookInfo VALUES (67,'The Secret Agent','Joseph Conrad','The place is London| and the time is the late 1800s. Mr. Verloc appears to be an unassuming owner of a bric-a-brac store| but he’s actually a spy for an unnamed country. When he’s summoned by his superiors and ordered to plant a bomb to foment unrest in English politics and society| he finds himself stuck in a more-than-uncomfortable situation.',94326,65.01,'5h 44m');
INSERT INTO BookInfo VALUES (69,'The Wood Beyond the World','William Morris','William Morris is famous in no small part for his contributions to defining the genre of modern fantasy literature| and The Wood Beyond the World is a classic example of that influence. Written in a purposefully-antiquated prose style reminiscent of Sir Thomas Malory or other aged fairy tales| The Wood Beyond the World can be difficult for some readers; but those who follow through will enjoy a charming and influential series of picaresque adventures.',50018,73.95,'3h 2m');
INSERT INTO BookInfo VALUES (70,'The House on the Borderland','William Hope Hodgson','The House on the Borderland is unique in several ways. The narrative itself is a double-frame narrative: the editor of the volume is presenting a manuscript he found under mysterious circumstances| describing the account of two fishermen who themselves discovered a hand-written account of the cosmic haunting of a recluse’s remote home.',51007,70.63,'3h 6m');
INSERT INTO BookInfo VALUES (71,'A Voyage to Arcturus','David Lindsay','On hearing the title A Voyage to Arcturus| one might picture an astronaut strapping themselves into a rocket and flying into space for a swashbuckling adventure. Nothing could be further from what this book actually is.',94139,76.11,'5h 43m');
INSERT INTO BookInfo VALUES (72,'The Religion of Nature Delineated','William Wollaston','Wollaston attempts to determine what rules for the conduct of life (that is| what religion) a conscientious and penetrating observer might derive simply from reasoning about the facts of the world around him| without benefit of divine revelation. He concludes that truth| reason| and morality coincide| and that the key to human happiness and ethical behavior is this: “let us by no act deny anything to be true which is true; that is: let us act according to reason.”',91261,58.66,'5h 32m');
INSERT INTO BookInfo VALUES (73,'The Autobiography of Benjamin Franklin','Benjamin Franklin','Benjamin Franklin is a man who needs little introduction. He wore many hats over the course of his fascinating life| from that of a printer| to an inventor| to a scientist| to a politician| a founding father and statesman| and even a postmaster-general. He was famous for all of these things in his day| but he was also famed for his keen insight into people and human nature| and his sparkling talent as a conversationalist.',64695,49.79,'3h 56m');
INSERT INTO BookInfo VALUES (75,'Suspiria de Profundis','Thomas De Quincey','The Suspiria is a collection of prose poems| or what De Quincey called “impassioned prose|” eratically written and published starting in 1854. Each Suspiria is a short essay written in reflection of the opium dreams De Quincey would experience over the course of his lifetime addiction| and they are considered by some critics to be some of the finest examples of prose poetry in all of English literature.',57828,52.43,'3h 31m');
INSERT INTO BookInfo VALUES (76,'The Moon Pool','Abraham Merritt','The Moon Pool| in novel form| is a combination and fix-up of two previously-published short stories: “The Moon Pool|” and “Conquest of the Moon Pool.” Initially serialized in All-Story Weekly| Merritt made the interesting choice of framing the novel as a sort of scientific retelling| going so far as to include footnotes from fictional scientists| to give this completely fantastic work an air of authenticity.',98708,71.95,'5h 59m');
INSERT INTO BookInfo VALUES (78,'The Secret Garden','Frances Hodgson Burnett','Mary’s parents fall ill and die| forcing her to be transplanted from India to the English countryside. She arrives at a strange and foreign country manor| where she discovers a long-neglected garden and hears strange sobbing noises at night.',82704,82.44,'5h 1m');
INSERT INTO BookInfo VALUES (79,'A Journal of the Plague Year','Daniel Defoe','The Plague is a disease that has a long and tragic history alongside humanity’s development of tightly-packed cities. A Journal of a Plague Year is a first-person narrative account of London’s last great plague outbreak in 1665| which killed an estimated 100|000 people in just 18 months.',94924,42.11,'5h 46m');
INSERT INTO BookInfo VALUES (81,'Cranford','Elizabeth Gaskell','Cranford was first serialized in Charles Dickens’ magazine Household Words between 1851 and 1853. The structureless nature of the stories| and the fact that Gaskell was busy writing her novel Ruth at the time the Cranford shorts were being published| suggests that she didn’t initially plan for Cranford to be a cohesive novel.',71681,63.53,'4h 21m');
INSERT INTO BookInfo VALUES (86,'The Jungle Book','Rudyard Kipling','The Jungle Book is a short collection of stories published by Kipling in various magazines between 1893 and 1894. Kipling spent both his early years and his late teenage years in India| and that upbringing is front and center in these stories—despite them being written while he was living in Vermont| in the United States.',51562,78.18,'3h 8m');
INSERT INTO BookInfo VALUES (89,'Little Women','Louisa May Alcott','Little Women is the classic coming-of-age tale of four sisters on their journey to adulthood. Though today it’s considered a classic| Little Women almost wasn’t written: Alcott wanted to publish a collection of short stories instead| but her publisher and her father pressed her to write a book that would appeal to a wide audience of young girls.',190800,74.83,'11h 34m');
INSERT INTO BookInfo VALUES (92,'The Luck of Barry Lyndon','William Makepeace Thackeray','The Luck of Barry Lyndon was first published as a serial in Fraser’s Magazine| then later as a complete volume entitled The Memoirs of Barry Lyndon| Esq.—a title Thackeray disliked| but that was selected by his publisher. Thackeray had great difficulty composing the novel| and found himself frequently frustrated in his attempts to get Barry out of yet another jam. Ultimately he was displeased with his work| and considered it one of his lesser novels.',127624,59.57,'7h 45m');
INSERT INTO BookInfo VALUES (98,'The Last of the Mohicans','James Fenimore Cooper','The Last of the Mohicans is one of the most famous tales of pioneer American adventure. Set during the French and Indian War| Mohicans tells the tale of the journey of two daughters to meet their father| a colonel| at Fort William Henry. The road is long and dangerous| and they| along with their American and Native guides| encounter adventure at each step.',147082,62.31,'8h 55m');
INSERT INTO BookInfo VALUES (102,'Short Fiction','Algis Budrys','Algis Budrys’ science fiction writing career is long and storied. This collection of seven of his early stories published in science fiction pulp magazines is a window into his imagination and style.',41762,75.71,'2h 32m');
INSERT INTO BookInfo VALUES (103,'The Big Time','Fritz Leiber','At the time of the release of this ebook edition of The Big Time| it remains the only Hugo-award-winning work in the public domain. That makes it a very special treasure indeed!',40388,75.34,'2h 27m');
INSERT INTO BookInfo VALUES (105,'The Wind in the Willows','Kenneth Grahame','The Wind in the Willows| the story of four animals and their adventures in the idyllic English countryside| started out as bedtime stories Grahame would tell his son. He eventually started writing them down| and finally produced this much-loved childrens classic.',59843,77.16,'3h 38m');
INSERT INTO BookInfo VALUES (106,'Short Fiction','Arthur Machen','Arthur Machen was a Welsh man of letters who wrote his most famous work in the late 1890s and early 1900s. While his body of work is wide| he’s perhaps best known for his supernaturally-flavored proto-horror short stories. The Great God Pan—perhaps his most famous work—along with “The Inmost Light” and The White People deeply influenced later writers like H. P. Lovecraft. Stephen King has gone so far as to call The Great God Pan “maybe the best [horror story] in the English language.”',104328,73.1,'6h 20m');
INSERT INTO BookInfo VALUES (109,'The Lost World','Arthur Conan Doyle','Even though Doyle is most famous for his Sherlock stories| he was also a prolific novelist| and The Lost World is one of his more famous non-Sherlock novels. Like many novels of the day| it was first published serially.',76468,70.23,'4h 39m');
INSERT INTO BookInfo VALUES (110,'David Copperfield','Charles Dickens','Like many of Dickens’ works| David Copperfield was published serially| then as a complete novel for the first time in 1850. Dickens himself thought of it as his favorite novel| writing in the preface that of all his works Copperfield was his favorite child. This isn’t surprising| considering that many of the events in the novel are semi-autobiographical accounts from Dickens’ own life.',361443,70.33,'21h 55m');
INSERT INTO BookInfo VALUES (114,'The Narrative of Arthur Gordon Pym of Nantucket','Edgar Allan Poe','Edgar Allan Poe is famed for his unsettling short stories| but he also wrote a full-length novel| his only one: The Narrative of Arthur Gordon Pym of Nantucket. Framed as the recollections of an adventurous stowaway| Pym begins as a swashbuckling adventure novel| and after growing increasingly weirder| ends on a surreal note worthy of the best of Poe’s short stories.',70790,51.21,'4h 18m');
INSERT INTO BookInfo VALUES (115,'The Picture of Dorian Gray','Oscar Wilde','The Picture of Dorian Gray was first published as a serial in Lippencott’s Monthly Magazine| and the publishers thought it would so offend readers that they removed nearly 500 words without Wilde’s approval. Wilde soon expanded it and republished it as a novel| including a short preface justifying his art. Even though his contemporaries considered it so offensive that some argued for his prosecution| Dorian Gray today survives as a classic philosophical novel that explores themes of aestheticism and double lives. Couched in Wilde’s trademark cutting wit| Dorian Gray is still being adapted today| with Dorian and his moldering portrait remaining cultural touchstones.',79768,75.5,'4h 51m');
INSERT INTO BookInfo VALUES (118,'The Jungle','Upton Sinclair','The Jungle is one of the most famous muckraking novels in modern history. Set in Chicago at the dawn of the 20th century| it tells the story of an immigrant Lithuanian family trying to make it in a new world both cruel and full of opportunity. Their struggles are in part a vehicle for Sinclair to shine a spotlight on the monstrous conditions of the meatpacking industry| to expose the brutal exploitation of immigrants and workers| and to espouse his more socialist worldview.',150912,72.8,'9h 9m');
INSERT INTO BookInfo VALUES (122,'Dubliners','James Joyce','Dubliners is a collection of picturesque short stories that paint a portrait of life in middle-class Dublin in the early 20th century. Joyce| a Dublin native| was careful to use actual locations and settings in the city| as well as language and slang in use at the time| to make the stories directly relatable to those who lived there.',68792,73.88,'4h 11m');
INSERT INTO BookInfo VALUES (123,'Walden','Henry David Thoreau','Walden is one of the more famous transcendentalist tracts in modern American literature. First published in 1854| Walden is an account of Thoreau’s famous experiment in solitude: spending over two years alone in a cabin near the wilderness.',106988,59.77,'6h 30m');
INSERT INTO BookInfo VALUES (124,'The Turn of the Screw','Henry James','One of the most famous ghost stories in literature| The Turn of the Screw earned its place in the annals of influential English novellas not for its qualities as a gothic ghost story| but rather for the many complex and subtle ways the reader can come to opposing conclusions as to tale’s very nature. Are the ghosts the governess sees real| or are they figments of her quiet insanity?',43377,79.3,'2h 38m');
INSERT INTO BookInfo VALUES (125,'Confessions of an English Opium-Eater','Thomas De Quincey','Thomas De Quincey spent much of his life addicted to the powerful drug opium. This book| first published anonymously in the London Magazine| is the autobiographical account of his addiction. De Quincey’s compelling language and frankness give the reader a window in to both the strange pleasures and the horrible pains of that famous drug.',36745,44.41,'2h 14m');
INSERT INTO BookInfo VALUES (126,'Dracula','Bram Stoker','Dracula is one of the most famous public-domain horror novels in existence| responsible for not just introducing the eponymous Count Dracula| but for introducing many of the common tropes we see in modern horror fiction.',162186,77.67,'9h 50m');
INSERT INTO BookInfo VALUES (127,'Pride and Prejudice','Jane Austen','Pride and Prejudice may today be one of Jane Austen’s most enduring novels| having been widely adapted to stage| screen| and other media since its publication in 1813. The novel tells the tale of five unmarried sisters and how their lives change when a wealthy eligible bachelor moves in to their neighborhood.',122665,61.16,'7h 27m');
INSERT INTO BookInfo VALUES (129,'The Worst Journey in the World','Apsley Cherry-Garrard','Illustrated by Edward A. Wilson.',241294,66.27,'14h 38m');
INSERT INTO BookInfo VALUES (130,'The Importance of Being Earnest','Oscar Wilde','The Importance of Being Earnest is Oscar Wilde’s most popular play today| enduring thanks to its easy humor| witty dialog| and clever satire. It was also one of his more successful plays| despite its first run being prematurely ended after only 86 performances. The main characters pretend to be other people in order to escape social obligations| with the resulting confusion of identities driving the plot and the humor behind it.',20900,70.09,'1h 16m');
INSERT INTO BookInfo VALUES (131,'Frankenstein','Mary Shelley','Mary Shelley (then Godwin) and Percy Bysshe Shelley were visiting their friend Lord Byron in Geneva one rainy summer. With the weather against them| they decided to spend their time writing ghost stories for each other. Frankenstein is Mary Shelley’s submission to their contest| later published anonymously in 1818.',78011,64.75,'4h 44m');
INSERT INTO BookInfo VALUES (132,'White Fang','Jack London','White Fang is Jack London’s companion novel to The Call of the Wild. In The Call of the Wild we follow a dog’s journey from domestication to wilderness| but in White Fang we see the opposite: a wild wolf-dog captured by men and eventually domesticated.',72797,81.22,'4h 25m');
INSERT INTO BookInfo VALUES (134,'The Mysterious Affair at Styles','Agatha Christie','The Mysterious Affair at Styles isn’t just Agatha Christie’s first Poirot novel| it’s currently the only Poirot novel in the public domain. It was written on a bet that Christie couldn’t write a detective novel in which the reader couldn’t deduce the criminal. Her attempt laid the foundation for one of literature’s most famous detectives.',57821,77.03,'3h 31m');
INSERT INTO BookInfo VALUES (137,'North of Boston','Robert Frost','North of Boston is Robert Frost’s second collection of poetry. It includes some of his more famous poems| like “Mending Wall|” “Home Burial|” and “After Apple-Picking.”',17940,93.34,'1h 6m');
INSERT INTO BookInfo VALUES (139,'The Call of the Wild','Jack London','Jack London spent nearly a year in Alaska and the Klondike| mining for gold and braving the Alaskan winter. There he was inspired to write what would become The Call of the Wild| one of his most famous novels. The Call of the Wild tells the tale of a domesticated dog stolen from his California family and sold to sledders in Alaska. As he adapts to the harsh and wild environment| he slowly sheds domestication and returns to his primal roots.',32031,77.37,'1h 57m');
INSERT INTO BookInfo VALUES (141,'Heart of Darkness','Joseph Conrad','Originally published serially as a three-part story| Heart of Darkness is a short but thematically complex novel exploring colonialism| humanity| and what constitutes a savage society. Set in the Congo in Central Africa| the tale is told in the frame of the recollections of one Charles Marlow| a captain of an ivory steamer. Marlow’s search for the mysterious and powerful “first-class agent” Kurtz gives way to a nuanced and powerful commentary on the horrors of colonialism| called by some the most analyzed work at university-level instruction.',38790,71.44,'2h 22m');
INSERT INTO BookInfo VALUES (149,'The Surprising Adventures of Baron Munchausen','Rudolph Erich Raspe','Baron Hieronymus Karl Friedrich| Freiherr von Münchhausen| was an actual baron living in 18th-century Hanover famous for entertaining his guests with outrageously-embellished tales of his wartime exploits—so much so that his nickname in German is Lügenbaron| or “Baron of Lies.” When Rudolph Eric Raspe| a writer and scientist living in England| heard of the Baron’s tales| he wrote his own versions centered around a fictional Baron Munchausen.',52643,46.03,'3h 12m');
